### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RonnyO** [ShizukuIchi/winXP#1]
Awesome work!
Just wondering what's the license for this project, before going ahead forking etc.

**Comment by ShizukuIchi** [comment]
Hi @RonnyO,

This project is licensed under the MIT License.

**Comment by RonnyO** [comment]
Cool! Thank you

**Comment by jserv** [comment]
Only the code should be considered as the governance of MIT License. However, the artwork SHOULD NOT be regarded. Explicit disclaimer about artwork and trademark information are necessary.

**Comment by ShizukuIchi** [comment]
Hi @jserv,
Thanks for your kind reminder. License in README updated
