### ISSUE TITLE
Minesweeper is not correct

### ISSUE THREAD

**Issue by benhk2005** [ShizukuIchi/winXP#11]
![Screenshot 2019-03-29 at 9 36 36 PM](https://user-images.githubusercontent.com/6396692/55236644-602c3900-526b-11e9-9416-c9fbf29198ae.png)
The bottom right hand corner shouldn't be two "1"? 🤔

**Comment by MarkFilus** [comment]
I think it's fine. A bomb with a cross over it means you put a flag where there was no bomb. Flags that are correct stay on the screen, and the real bombs reveal themselves.

**Comment by ShizukuIchi** [comment]
Hey @benhk2005! As @MarkFilus metioned, I'm trying to make all functionality the same as origin Minesweeper so I think it's not an "issue".

Thanks though!
