### ISSUE TITLE
double tap to maximize the app window

### ISSUE THREAD

**Issue by mostafa-kheibary** [ShizukuIchi/winXP#118]
* maximize window by double tap on top bar of the App

![Screenshot 2022-04-30 054601](https://user-images.githubusercontent.com/58364608/166084877-fdcb6a0d-6c32-412f-af13-4a84cdd9a258.png)

**Comment by Arciiix** [comment]
Fixed in #120

**Comment by ShizukuIchi** [comment]
Close by #125, thanks. 🙂
