### ISSUE TITLE
No Paint

### ISSUE THREAD

**Issue by alisd23** [ShizukuIchi/winXP#2]
It's not really Windows XP until you have Paint. 

This is a critical missing feature which is preventing us from migrating over.

Thanks

**Comment by crutchcorn** [comment]
It even exists already 

https://github.com/1j01/jspaint

**Comment by alisd23** [comment]
Open source is great

**Comment by IgorMacGregor** [comment]
Hi everyone, I would be very happy to work on this issue ! Do you think I could directly copy/paste (with some changes of course) the jspaint into winxp ?
Thanks !

**Comment by ShizukuIchi** [comment]
can't agree more. #44
