### ISSUE TITLE
Winamp?

### ISSUE THREAD

**Issue by captbaritone** [ShizukuIchi/winXP#3]
Great job on this!

I maintain a JS clone of Winamp which is available on NPM. Would be cool to see it integrated here.

https://github.com/captbaritone/webamp

**Comment by ShizukuIchi** [comment]
Hey @captbaritone, I have seen this before! I'll find time to add it. 😃

**Comment by captbaritone** [comment]
Awesome! Feel free to drop by our Discord (link in the readme). I can help in, more or less, real time. There are also some other similarly minded folks who hang out there.

**Comment by ShizukuIchi** [comment]
Finally! #38
