### ISSUE TITLE
Clock shows 0 when it is supposed to be 12

### ISSUE THREAD

**Issue by ghostslayer989** [ShizukuIchi/winXP#33]
When it is 12 PM (and AM?) it shows 0 on the clock. As shown in the image.
WinXP is top. Windows 10 is bottom.
![time](https://user-images.githubusercontent.com/45863583/55420861-fbf8c600-5545-11e9-8ae3-95b79d682c18.PNG)

**Comment by DiscordBee** [comment]
Got the same problem

**Comment by ShizukuIchi** [comment]
It should be 12 for both AM and PM.
I will fix it, thanks!
