### ISSUE TITLE
Add functionality to other desktop applications

### ISSUE THREAD

**Issue by xianrusso** [ShizukuIchi/winXP#4]
First and foremost, I love this project idea!  It brings me back to the early days of playing solitaire and minesweeper on my father's Dell.  This is a trivial suggestion, but I think it would be fun to add functionality to the other desktop applications, such as Spider Solitaire, Calculator, and Hearts.  I'd be more than happy to help with this, of course.

**Comment by ShizukuIchi** [comment]
Hello @xianrusso,

Thank you!

Feel free to make PR! Just  open an issue before starting work on it.
