### ISSUE TITLE
Dependabot.

### ISSUE THREAD

**Issue by ghostslayer989** [ShizukuIchi/winXP#41]
Hope you don't mind me sending dependabot's PRs which were for my fork of WinXP over to this repo so you can update the dependencies.

**Comment by ShizukuIchi** [comment]
Hey @ghostslayer989 , which packages?

**Comment by ghostslayer989** [comment]
It does all the package.json packages. Like the ReactJS updates I sent you a day or 2 ago.

**Comment by ShizukuIchi** [comment]
I'll suspend this since there isn't necessary upgrades now. Thanks though!
