### ISSUE TITLE
Thumbnail previews in Taskbar

### ISSUE THREAD

**Issue by padraigfl** [ShizukuIchi/winXP#42]
![image](https://user-images.githubusercontent.com/14135877/55633069-7bd79800-57b3-11e9-8278-e4f972093db2.png)

Pretty sure a copy of copying the current state of the window in question and css transform: scale could pull this off easily enough. It'd be hacky as hell but would look super neat.

**Comment by ShizukuIchi** [comment]
Really cool!
But I might not add it since origin XP doesn't have this feature.
