### ISSUE TITLE
No readme to install ?

### ISSUE THREAD

**Issue by mouarfff** [ShizukuIchi/winXP#68]
Sorry if i'm stupid but i don't find the way to install it ?

**Comment by maracuja-juice** [comment]
It's not in the readme (yet?)

The steps are:
1. clone
2. yarn
3. yarn start

**Comment by mouarfff** [comment]
Thx !
i search about yarn  and debian and i found it :
https://yarnpkg.com/en/docs/install#debian-stable

I follow instruction and now it's almost ok,
i can go into http://server:5000

now i will learn more about it and proxyfy it in apache...

It's diffcult if you don't know yarn/npm etc ...
