### ISSUE TITLE
I made a similar webOS system

### ISSUE THREAD

**Issue by OXOYO** [ShizukuIchi/winXP#9]
This system is so beautiful, the system is highly restored.

I made a similar webOS system. It is based on Vue and koa.
[X-WebDesktop-Vue](https://github.com/OXOYO/X-WebDesktop-Vue)

**Comment by disjfa** [comment]
Lol, lets manage the "apps". I need a minesweeper for my win3.1 edition

https://disjfa.github.io/vue-win-3.1/
https://github.com/disjfa/vue-win-3.1

**Comment by ShizukuIchi** [comment]
Great work! @OXOYO 
@disjfa I would like to see a vue version minesweeper.XD

**Comment by disjfa** [comment]
Nobody helps me, so i had to implement it myself....
https://vue-minesweeper.js.org/
